// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include <stdio.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Subsystems/Drivetrain.h"
#include "Subsystems/FuelHandler.h"
#include "Subsystems/GearHandler.h"
#include "Subsystems/Lighting.h"
#include "Subsystems/Logger.h"
#include "Subsystems/Smartdash.h"
#include "Subsystems/Vision.h"
#include "Subsystems/Winch.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"


class Robot : public IterativeRobot {
public:
	std::unique_ptr<Command> autonomousCommand;
	std::unique_ptr<Command> autoCmd;

	// -------------- Auto Selection -------------
	frc::SendableChooser<std::string*> locChooser;
	frc::SendableChooser<std::string*> actionChooser;
	frc::SendableChooser<std::string*> tgtChooser;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
	Timer sysTimer;

	const float DEGREETORADIANCONST = 0.0174533;				// Degrees * Constant = Radians
	const float RADIANSTODEGREECONST = 57.295791;				// Constant / Radians = Degrees
	// -------------------------------------------

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<Drivetrain> drivetrain;
    static std::shared_ptr<FuelHandler> fuelHandler;
    static std::shared_ptr<Vision> vision;
    static std::shared_ptr<Lighting> lighting;
    static std::shared_ptr<Winch> winch;
    static std::shared_ptr<Smartdash> smartdash;
    static std::shared_ptr<Logger> logger;
    static std::shared_ptr<GearHandler> gearHandler;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestPeriodic();

	void UserInit();
};
#endif
