// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoRightGearCmdGrp.h"
#include "AutoDriveFwdCmd.h"
#include "DrivePointTurnCmd.h"
#include "GearTranToPosCmd.h"
#include "DelayCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoRightGearCmdGrp::AutoRightGearCmdGrp() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

		// ------- Move forward toward Turning Point -----------------
		// 							(tgtDist, accelPwr, cruisePwr, decelPwr, slowPwr, stopPwr, accelDist, decelDist, slowSpeed, stopDist, TO, Mode)
		AddParallel(new AutoDriveFwdCmd(48,     0.25,     0.45,      -0.1,     0.1,    -0.15,     3,         6,        10,        0.5,    5,  0));

		// ------- Translate to Center while moving forward -----------------
		// Params : (Speed, Position, Mode)  Mode 1=Get Tgt Data from Vision, 2=Get from Position param
		AddSequential(new GearTranToPosCmd( 0.4, 0.0, 2));

		// ------- Turn Robot Left (CCW) to face the target -----------------
		// (Angle, Speed, Timeout, Mode (0=by angle, 1=Left Side CW, 2=Right Side CCW)
		AddSequential(new DrivePointTurnCmd(-10, 0.5, 8, 2));

		// -------- Delay 2/10'second for vision to get image ------------
		AddSequential(new DelayCmd( 0.2));

		// ------- Translate to Position based on Vision when in front of target --------------
		// Params : (Speed, Position, Mode)  Mode 1=Get Tgt Data from Vision, 2=Get from Position param
		AddSequential(new GearTranToPosCmd( 0.4, 0.0, 1));
 }
