// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "SmartdashUpdateCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

SmartdashUpdateCmd::SmartdashUpdateCmd(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::smartdash.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void SmartdashUpdateCmd::Initialize() {
	std::cout << "Running SmartdashUpdateCmd" << std::endl;
	Robot::logger->appendLog("Starting Smartdashboard Update");
	cnt = 1;
}

// Called repeatedly when this Command is scheduled to run
void SmartdashUpdateCmd::Execute() {
	if (cnt < 5){									// Only update dashboard every 5 cycle or 10 x second
		cnt ++;
		return;
	}
	cnt = 1;

	Robot::drivetrain->Update_Smartdashboard(0);
	Robot::lighting->Update_Smartdashboard(0);
	Robot::gearHandler->DisplaySmartdashSimple();
	Robot::winch->DisplaySmartdashSimple();
	Robot::fuelHandler->UpdateSmartDashboard();
	Robot::vision->Update_Smartdashboard(0);
}

// Make this return true when this Command no longer needs to run execute()
bool SmartdashUpdateCmd::IsFinished() {
	    return false;
}

// Called once after isFinished returns true
void SmartdashUpdateCmd::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SmartdashUpdateCmd::Interrupted() {

}

// --------------------------- User Defined methods ----------------------



