// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoCtrGearCmdGrp.h"
#include "AutoDriveFwdCmd.h"
#include "GearTranToPosCmd.h"
#include "DelayCmd.h"
#include "GearPushCmd.h"
#include "DriveReverseCmd.h"
#include "VisionUpdate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoCtrGearCmdGrp::AutoCtrGearCmdGrp() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

	//                             (tgtDist, accelPwr, cruisePwr, decelPwr, slowPwr, stopPwr, accelDist, decelDist, slowSpeed, stopDist, TO, Mode)
	AddSequential(new AutoDriveFwdCmd(43.0,     0.35,      0.35,      -0.0,     0.05,    -0.20,      3,       3,         0.0,       0.2,   4,   0));


	// -------- Delay 2/10'second for vision to get image ------------
	AddSequential(new DelayCmd(0.2));

	// -------- Update Vision Data ------------
	AddSequential(new VisionUpdate());

	// this will drive forward with vision to tgt heading indicated by vision subsystem
	//							   (tgtDist, accelPwr, cruisePwr, decelPwr, slowPwr, stopPwr, accelDist, decelDist, slowSpeed, stopDist, TO, Mode)
	 AddSequential(new AutoDriveFwdCmd(38,     0.25,      0.25,      -0.0,     0.05,    -0.20,      3,       3,         0.0,       0.2,   3,   1));

	// -------- DPush the gear onto the post ------------
	AddSequential( new GearPushCmd(1));
	AddSequential( new GearPushCmd(1));

	// ------- Translate to Center while moving forward -----------------
	// Params : (Speed, Position, Mode)  Mode 1=Get Tgt Data from Vision, 2=Get from Position param
	//AddSequential(new GearTranToPosCmd( 0.4, 0.0, 2));

	// -------- Delay 2/10'second for vision to get image ------------
	//AddSequential(new DelayCmd( 0.2));

	// ------- Translate to Position based on Vision when in front of target --------------
	// Params : (Speed, Position, Mode)  Mode 1=Get Tgt Data from Vision, 2=Get from Position param
	//AddSequential(new GearTranToPosCmd( 0.4, 0.0, 1));

	// -------- Drive to probe to place gear -----------------------------
	//                             (tgtDist, accelPwr, cruisePwr, decelPwr, slowPwr, stopPwr, accelDist, decelDist, slowSpeed, stopDist, TO, Mode)
		//AddSequential(new AutoDriveFwdCmd(36, 0.25, 0.35, -0.1, 0.1, -0.15, 3, 6, 10, 0.5, 5));
	//AddSequential(new AutoDriveFwdCmd(24,     0.25,      0.25,      -0.0,     0.05,    -0.20,      3,       3,         0.0,        0.2,   3,   1));

	// -------- DPush the gear onto the post ------------
	//AddParallel(new GearPushCmd(1));

	// -------- Back away after placing gear onto post ------------
	//	              DriveReverseCmd(   Dist ,   Speed, Mode, TimeOut)
	//AddSequential(new DriveReverseCmd(    8	,    -0.3,     0,    5));

 }
