// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEREVERSECMD_H
#define DRIVEREVERSECMD_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveReverseCmd: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	DriveReverseCmd(double Dist, double Speed, double Mode, double TO);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

    double m_Dist;
    double m_Speed;
    double m_Mode;
    double m_TO;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	std::string line;

	//const float kEncoderConvPtTurn =0.3134008;	// degrees rotation per encoder cnt.

	int LeftEncoderValue;
	int RightEncoderValue;
	int state;
};

#endif
