// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "GearEjectBackupCmdGrp.h"
#include "GearEjectCmd.h"
#include "GearRetractCmd.h"
#include "DriveReverseCmd.h"
#include "GearTranToPosCmd.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

GearEjectBackupCmdGrp::GearEjectBackupCmdGrp() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

	// ------- Eject gear -------
	AddParallel(new GearEjectCmd());

	// ------- Back away from Peg -------
	//				  DriveReverseCmd(   Dist ,   Speed, Mode, TimeOut)
	AddSequential(new DriveReverseCmd(    8	,    -0.3,     0,    5));

	// ------- Retract Eject Bar -------
	AddParallel(new GearRetractCmd());

	// ------- Translate to Ctr position to be ready to get new Gear -------
	// Params :                       (Speed, Position, Mode)  Mode 0= Ctr, 1=Tgt from Vision, 2= Position param
	AddSequential(new GearTranToPosCmd( 0.4,    0.0,     0));	// Move to Center

 }
